#!/usr/bin/env python3
"""
survey.py -- stage 2 of the declutter pipeline.

Walk the target directory once and write down everything the planner needs in
order to make decisions: every file with its hash, size, and date; a one-row
summary of each top-level entry; groups of byte-identical files; dependency and
build directories that are pure bulk; and files whose name or contents look
like a credential.

This script is strictly read-only. It opens files to hash them and to sniff for
secrets, but it never writes anywhere except the work directory.

    "Midway upon the journey of our life I found myself within a forest dark."
        -- Dante Alighieri, Inferno, Canto I

Usage:
    survey.py <target> --work <workdir> [--hash-max-mb N]

Outputs, all inside <workdir>/:
    manifest.tsv     hash  size  mtime  flags  path       (one row per file)
    toplevel.tsv     one row per top-level entry: counts, dates, git state, env bloat
    duplicates.tsv   groups of byte-identical files
    bloat.tsv        dependency/build directories and their sizes
    secrets.tsv      files that look like credentials; values are never written
    summary.json     totals and histograms
"""

import argparse
import collections
import hashlib
import json
import os
import re
import subprocess
import sys
import time


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Directory names that hold regenerable dependency or build output. The
# survey measures them but does not hash their contents, and the planner
# usually stages them for deletion.
#
#     "The things you own end up owning you."
#         -- Fight Club
ENV_DIRS = {
    "venv", ".venv", "env", "node_modules", ".terraform", "__pycache__", ".idea",
    ".pytest_cache", "site-packages", ".tox", "build", "dist", ".gradle", ".cache",
    "Pods", "DerivedData", ".mypy_cache",
    "@eaDir",            # Synology NAS thumbnail/index cache, regenerated by DSM
}

# A filename that matches this pattern is flagged as a possible credential.
# It is deliberately broad; the planner sorts real hits from false positives
# (Keynote's .key, a public PGP key, a "recovery guide" PDF).
SECRET_NAME = re.compile(
    r"(^\.env$|^\.env\.|\.pem$|\.key$|\.asc$|\.gpg$|_rsa$|id_ed25519|creds|credential|secret|"
    r"token|apikey|api_key|passw|\.p12$|\.pfx$|backup.?codes|recovery|\.kdbx$|\.ovpn$)",
    re.I,
)

# Byte patterns that mean "there is a live secret in this file": private key
# headers and the recognisable prefixes of a few common API tokens. Only files
# under 1 MB are sniffed, and only outside dependency and git directories.
SECRET_CONTENT = re.compile(
    rb"(BEGIN (RSA|PGP|OPENSSH|EC|DSA) PRIVATE KEY|AKIA[0-9A-Z]{16}|xox[baprs]-[0-9A-Za-z-]{10,}|"
    rb"ghp_[0-9A-Za-z]{30,}|sk-[0-9A-Za-z]{20,}|consumer_secret\s*=|access_token_secret\s*=|"
    rb"BEGIN PGP MESSAGE)"
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def md5(p):
    """Return the MD5 hex digest of a file, read in 1 MB chunks.

    MD5 is used for identity, not security: the question is "are these two
    files the same bytes", and for that it is fast and good enough.
    """
    h = hashlib.md5()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def git_info(p):
    """Summarise a git repository at path p.

    Returns (remote, last_commit_date, dirty_count, unpushed_count). Every
    field degrades gracefully: no remote becomes "(no remote)", no upstream
    branch makes the unpushed count "?". The planner uses these to refuse to
    delete anything with work that exists nowhere else.
    """
    def g(*args):
        try:
            return subprocess.run(["git", "-C", p, *args],
                                  capture_output=True, text=True, timeout=20).stdout.strip()
        except Exception:
            return ""

    remote = g("remote", "get-url", "origin") or "(no remote)"
    last = g("log", "-1", "--format=%cs") or "-"
    dirty = len(g("status", "--porcelain").splitlines())
    ahead = g("rev-list", "--count", "@{u}..HEAD") or "?"

    return remote, last, dirty, ahead


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("target")
    ap.add_argument("--work", required=True)
    ap.add_argument("--hash-max-mb", type=int, default=500,
                    help="skip hashing files larger than this (default 500)")
    # Accepted for compatibility; env and git contents are always left unhashed.
    ap.add_argument("--no-hash-envs", action="store_true", default=True,
                    help="do not hash files inside dependency dirs or .git (default on)")
    a = ap.parse_args()

    t = os.path.abspath(os.path.expanduser(a.target))
    os.makedirs(a.work, exist_ok=True)

    # Tiny convenience: W("name") opens an output file in the work directory.
    W = lambda name: open(os.path.join(a.work, name), "w")

    # Accumulators for the walk below.
    manifest = []                                # (hash, size, mtime, flags, relpath)
    by_hash = collections.defaultdict(list)      # hash -> [relpath, ...] for duplicate detection
    bloat = []                                   # (bytes, files, relpath) per dependency dir
    secrets = []                                 # (relpath, matched_by, size)
    ext_hist = collections.Counter()             # extension -> count
    year_hist = collections.Counter()            # year of mtime -> count
    total_bytes = 0
    top_stats = {}                               # top-level entry -> {files, bytes, oldest, newest, env_bytes}

    # The work directory usually lives inside the target. Skip it so the
    # pipeline's own artifacts never show up in the inventory.
    work_abs = os.path.abspath(a.work)

    # -- The walk ----------------------------------------------------------
    for root, dirs, files in os.walk(t):
        dirs[:] = [d for d in dirs if os.path.abspath(os.path.join(root, d)) != work_abs]

        rel_root = os.path.relpath(root, t)
        top = rel_root.split(os.sep)[0] if rel_root != "." else None
        in_git = ".git" in rel_root.split(os.sep)

        # Measure each dependency directory as a whole. We still descend into
        # it below (so the manifest is complete), but its files are flagged
        # "env" and never hashed.
        for d in list(dirs):
            if d in ENV_DIRS:
                p = os.path.join(root, d)
                sz = n = 0

                for r2, _, f2 in os.walk(p):
                    for f in f2:
                        try:
                            sz += os.lstat(os.path.join(r2, f)).st_size
                            n += 1
                        except OSError:
                            pass

                bloat.append((sz, n, os.path.relpath(p, t)))

                if top:
                    top_stats.setdefault(top, {}).setdefault("env_bytes", 0)
                    top_stats[top]["env_bytes"] += sz

        in_env = any(part in ENV_DIRS for part in rel_root.split(os.sep))

        for f in files:
            # Finder's per-folder metadata file is noise everywhere.
            if f == ".DS_Store":
                continue

            p = os.path.join(root, f)
            try:
                st = os.lstat(p)
            except OSError:
                continue

            rel = os.path.relpath(p, t)

            # Flags tell verify.py how this row was recorded.
            flags = []
            if in_git:
                flags.append("git")
            if in_env:
                flags.append("env")
            if os.path.islink(p):
                flags.append("link")

            # Hash unless the file is inside git or an env dir, is a symlink,
            # or is bigger than the caller wants to read. verify.py falls
            # back to size + name for rows recorded with "-".
            h = "-"
            skip_hash = (in_git or in_env or os.path.islink(p)
                         or st.st_size > a.hash_max_mb * 1024 * 1024)
            if not skip_hash:
                try:
                    h = md5(p)
                except OSError:
                    h = "-"

            mtime = time.strftime("%Y-%m-%d", time.localtime(st.st_mtime))
            manifest.append((h, st.st_size, mtime, ",".join(flags) or "-", rel))

            # Statistics and secret sniffing apply only to "real" content,
            # not to git internals or dependency trees.
            if not (in_git or in_env):
                total_bytes += st.st_size
                ext_hist[os.path.splitext(f)[1].lower() or "(none)"] += 1
                year_hist[mtime[:4]] += 1

                if h != "-" and st.st_size > 0:
                    by_hash[h].append(rel)

                why = []
                if SECRET_NAME.search(f):
                    why.append("name")
                if st.st_size < 1_000_000 and not os.path.islink(p):
                    try:
                        with open(p, "rb") as fh:
                            if SECRET_CONTENT.search(fh.read()):
                                why.append("content")
                    except OSError:
                        pass
                if why:
                    secrets.append((rel, "+".join(why), st.st_size))

            # Roll the file up into its top-level entry's summary.
            if top:
                s = top_stats.setdefault(top, {})
                s["files"] = s.get("files", 0) + 1
                s["bytes"] = s.get("bytes", 0) + st.st_size
                s["newest"] = max(s.get("newest", "0000"), mtime)
                s["oldest"] = min(s.get("oldest", "9999"), mtime)

    # -- manifest.tsv ------------------------------------------------------
    manifest.sort(key=lambda r: r[4])

    with W("manifest.tsv") as fh:
        fh.write("hash\tsize\tmtime\tflags\tpath\n")
        for r in manifest:
            fh.write("\t".join(map(str, r)) + "\n")

    # -- toplevel.tsv ------------------------------------------------------
    #
    # One row per entry the planner has to make a decision about. Files get
    # their own stat; directories get the rolled-up numbers from the walk;
    # git repos additionally get their remote and push state.
    with W("toplevel.tsv") as fh:
        fh.write("entry\tkind\tfiles\tbytes\tenv_bytes\toldest\tnewest\t"
                 "git_remote\tgit_last_commit\tgit_dirty\tgit_ahead\n")

        for e in sorted(os.listdir(t), key=str.lower):
            if e == ".DS_Store" or os.path.abspath(os.path.join(t, e)) == work_abs:
                continue

            p = os.path.join(t, e)
            s = top_stats.get(e, {})

            if os.path.islink(p):
                kind = "link"
            elif os.path.isdir(p):
                kind = "git" if os.path.exists(os.path.join(p, ".git")) else "dir"
            else:
                kind = "file"
                try:
                    st = os.lstat(p)
                    day = time.strftime("%Y-%m-%d", time.localtime(st.st_mtime))
                    s = {"files": 1, "bytes": st.st_size, "oldest": day, "newest": day}
                except OSError:
                    pass

            gi = git_info(p) if kind == "git" else ("-", "-", "-", "-")

            fh.write("\t".join(map(str, [
                e, kind, s.get("files", 0), s.get("bytes", 0), s.get("env_bytes", 0),
                s.get("oldest", "-"), s.get("newest", "-"), *gi,
            ])) + "\n")

    # -- duplicates.tsv, bloat.tsv, secrets.tsv ----------------------------
    dup_groups = [(k, v) for k, v in by_hash.items() if len(v) > 1]

    with W("duplicates.tsv") as fh:
        fh.write("hash\tcount\tpaths\n")
        for k, v in sorted(dup_groups, key=lambda kv: -len(kv[1])):
            fh.write(f"{k}\t{len(v)}\t" + " | ".join(sorted(v)) + "\n")

    with W("bloat.tsv") as fh:
        fh.write("bytes\tfiles\tpath\n")
        for sz, n, p in sorted(bloat, reverse=True):
            fh.write(f"{sz}\t{n}\t{p}\n")

    # Only the path, the reason it matched, and the size are recorded. The
    # matching bytes themselves are never written anywhere.
    with W("secrets.tsv") as fh:
        fh.write("path\tmatched_by\tsize\n")
        for r in secrets:
            fh.write("\t".join(map(str, r)) + "\n")

    # -- summary.json ------------------------------------------------------
    summary = {
        "target": t,
        "surveyed_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "files": len(manifest),
        "bytes_excluding_env_and_git": total_bytes,
        "top_level_entries": len([e for e in os.listdir(t) if e != ".DS_Store"]),
        "duplicate_groups": len(dup_groups),
        "duplicate_extra_files": sum(len(v) - 1 for _, v in dup_groups),
        "env_bytes": sum(b[0] for b in bloat),
        "secret_candidates": len(secrets),
        "extensions_top": ext_hist.most_common(20),
        "years": sorted(year_hist.items()),
    }

    with W("summary.json") as fh:
        json.dump(summary, fh, indent=1)

    print(json.dumps(summary, indent=1))


if __name__ == "__main__":
    main()
